
server:
  port: 8002
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  application:
    name: multiple-datasource-example
mysql:
  udemy:
    datasource:
      url: { REQUIRED }
      username: { REQUIRED }
      password: { REQUIRED }
      driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      hibernate:
        ddl-auto: create
    show-sql: true
    sql:
      init:
        mode: always
  tahauddin:
    datasource:
      url: { REQUIRED }
      username: { REQUIRED }
      password: { REQUIRED }
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      hibernate:
        ddl-auto: create
    show-sql: true
    sql:
      init:
        mode: always